# Generated by Django 2.1.7 on 2019-03-26 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ProviderChoice.GCE', 'Google'), ('ProviderChoice.EC2', 'EC2'), ('ProviderChoice.AZURE', 'Azure')], max_length=8)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('age', models.DurationField(default=datetime.timedelta(0))),
                ('active', models.BooleanField(default=False)),
                ('instance_id', models.CharField(max_length=200, unique=True)),
                ('region', models.CharField(default='', max_length=64)),
                ('csp_info', models.TextField(default='')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together={('provider', 'instance_id')},
        ),
    ]
