# Generated by Django 3.0.2 on 2020-02-18 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0004_auto_20190905_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='ttl',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
