# Generated by Django 3.1.4 on 2022-07-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0005_instance_max_age'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together={('provider', 'instance_id', 'vault_namespace')},
        ),
    ]
