# Generated by Django 3.1.4 on 2022-07-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0006_auto_20220720_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='instance_id',
            field=models.CharField(max_length=200),
        ),
    ]
