# Generated by Django 4.0.6 on 2022-10-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0007_auto_20220720_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
    ]
