# Generated by Django 4.0.6 on 2022-12-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0008_instance_ignore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CspInfo',
            fields=[
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ocw.instance')),
                ('tags', models.TextField(default='')),
                ('type', models.CharField(max_length=200)),
            ],
        ),
    ]
