# Generated by Django 4.0.6 on 2023-01-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0009_cspinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='csp_info',
        ),
    ]
