# Generated by Django 4.0.10 on 2023-06-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0010_remove_instance_csp_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='provider',
            field=models.CharField(choices=[('GCE', 'Google'), ('EC2', 'EC2'), ('AZURE', 'Azure'), ('OSTACK', 'Openstack')], max_length=8),
        ),
    ]
