# Generated by Django 4.2.4 on 2023-08-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0011_alter_instance_provider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='vault_namespace',
            new_name='namespace',
        ),
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together={('provider', 'instance_id', 'namespace')},
        ),
    ]
