# Generated by Django 5.0.9 on 2024-09-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0012_rename_vault_namespace_instance_namespace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instance',
            name='notified',
        ),
        migrations.AlterField(
            model_name='instance',
            name='provider',
            field=models.CharField(choices=[('GCE', 'Google'), ('EC2', 'EC2'), ('AZURE', 'Azure')], max_length=8),
        ),
    ]
