# Generated by Django 5.1.7 on 2025-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0013_remove_instance_notified_alter_instance_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='deleting_since',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the instance entered DELETING state', null=True),
        ),
    ]
