coverage:
  round: up
  range: "70..100"
  status:
    project:
      default:
        target: auto
        threshold: 0%
        paths:
          - "ocw"
        branches:
          - master
        if_ci_failed: ignore
        informational: true
        only_pulls: true
    patch:
      default:
        target: auto
        threshold: 0%
        paths:
          - "ocw"
        branches:
          - master
        if_ci_failed: ignore
        informational: true
        only_pulls: true
