FROM ghcr.io/suse/pcw_base_k8s:master

# Copy program files only
COPY ocw /pcw/ocw/
COPY webui/PCWConfig.py /pcw/webui/PCWConfig.py
COPY cleanup_k8s.py LICENSE README.md setup.cfg /pcw/

ENV PATH ${PATH}:/opt/google-cloud-sdk/bin/

WORKDIR /pcw

CMD ["python3", "cleanup_k8s.py"]
