# Generated by Django 2.1.3 on 2019-01-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('instance_id', models.CharField(max_length=200, unique=True)),
                ('region', models.CharField(default='', max_length=64)),
                ('csp_info', models.TextField(default='')),
            ],
        ),
    ]
