---
# See https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

name: PCW images build and push

on:
  release:
    types: [published]
  push:
    branches: '**'
  pull_request:
    types: [opened, reopened, edited, synchronize]

env:
  REGISTRY: ghcr.io
  PCW_IMAGE_PREFIX: ${{ github.repository }}

jobs:
  build:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suffix: [main, k8s]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ env.PCW_IMAGE_PREFIX }}_${{ matrix.suffix }}

      - name: Build Docker image (PCW)
        if: ${{ matrix.suffix == 'main' }}
        uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003
        with:
          context: .
          file: containers/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build Docker image (K8S)
        if: ${{ matrix.suffix == 'k8s' }}
        uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003
        with:
          context: .
          file: containers/Dockerfile_${{ matrix.suffix }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suffix: [main, k8s]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.REGISTRY }}/${{ env.PCW_IMAGE_PREFIX }}_${{ matrix.suffix }}

      - name: Build and push Docker image (PCW)
        if: ${{ matrix.suffix == 'main' }}
        uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003
        with:
          context: .
          file: containers/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push Docker image (K8S)
        if: ${{ matrix.suffix == 'k8s' }}
        uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003
        with:
          context: .
          file: containers/Dockerfile_${{ matrix.suffix }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
